---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and php package and updates cache
    package: # we can write apk for ubuntu or dnf for centos, package is generic and refers to all
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
