---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 and php package
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
